# =============================================================================
# HYBRID EMAIL ENGINE - Prompts & Templates
# =============================================================================
# Generates high-precision outreach emails by combining:
#   1. Dynamic AI Hook (Sentence 1) - Generated by OpenAI based on trigger type
#   2. Static Value Proposition (Rest of Email) - Hard-coded, never changes
# =============================================================================

# -----------------------------------------------------------------------------
# PART 1: THE STATIC BODY TEMPLATE
# -----------------------------------------------------------------------------
# Hard-coded text. It does NOT change.

STATIC_BODY_TEMPLATE = """We specialize in "Fiduciary Risk Audits"—measuring exactly where your management narrative diverges from market reality (the "Narrative Gap").

Most Boards rely on feedback filtered through brokers, creating a blindspot on true investor sentiment. We fix that by analyzing the raw, unvarnished perception of your register.

I have a Strategic Diagnostic prepared for {company_name} that identifies specific friction points your current reporting may be missing.

Do you want to see the audit before your next Board pack goes out?

Best,
{sender_name}
QuantiFire"""


# -----------------------------------------------------------------------------
# PART 2: THE OPENAI META-PROMPTS (The Brain)
# -----------------------------------------------------------------------------
# When a trigger is hit, use the corresponding prompt to generate [AI_HOOK_GOES_HERE]

# Scenario A: Event Trigger (CMD / Investor Day)
EVENT_TRIGGER_PROMPT = """You are a sophisticated Investor Relations consultant. Write one single sentence to open an email to {contact_name} at {company_name}.

Context: They just announced a Capital Markets Day (CMD) on {event_date}.
Additional Details: "{event_description}"

Goal: Connect the high stakes of a CMD to the risk of being misunderstood.

Tone: Professional, direct, slightly provocative. No fluff.

Strict Output Format: Just the sentence. No quotes."""


# Scenario B: Leadership Trigger (New CFO / Head of IR)
LEADERSHIP_TRIGGER_PROMPT = """You are a sophisticated Investor Relations consultant. Write one single sentence to open an email to {contact_name} at {company_name}.

Context: They were just appointed as the new {role}.
Additional Details: "{event_description}"

Goal: Frame their arrival as the perfect time to "audit" the legacy perception they inherited.

Tone: Helpful, authoritative.

Strict Output Format: Just the sentence. No quotes."""


# Scenario C: Volatility Trigger (Stock Drop)
VOLATILITY_TRIGGER_PROMPT = """You are a sophisticated Investor Relations consultant. Write one single sentence to open an email to {contact_name} at {company_name}.

Context: Their stock is down {performance} or underperforming the sector.
Additional Details: "{event_description}"

Goal: Frame the price drop not as a failure, but as a 'Narrative Gap' (the market missing the value).

Tone: Fiduciary, objective, not alarmist.

Strict Output Format: Just the sentence. No quotes."""


# =============================================================================
# FOUNDER VOICE ARCHETYPES (Warm Intelligence)
# =============================================================================
# Protocol: Warm Intelligence. Thoughtful peer observing market inefficiency.
# Key Rules: No "Fake Surprise", Financial Literacy (Valid Peers), Defense Frame.

# System directive for all archetypes
ANALYST_SYSTEM_PROMPT = """You are a thoughtful startup founder writing a personal, high-stakes email to a CFO or Head of IR. 
Your tone is "Warm Intelligence." You are not a hype-man; you are a peer quietly observing a market inefficiency.

STRICT DRAFTING RULES:
1. Tone: Warm, level-headed, financially literate.
2. No "Fake Surprise": NEVER use words like "Intriguing", "Puzzled", "Crazy", "Soaring", "Love".
3. Use phrases like: "It strikes me...", "It suggests...", "It feels like...", "I noticed a divergence..."
4. Financial Literacy: Never compare across different sectors (e.g. Insurance vs Banking). If the context has a bad peer match, ignore the peer and focus on the sector index or the company's own narrative.
5. The "Defense" Frame: Always frame a low stock price as a "Misunderstanding" by the market, not a failure.
   - Bad: "Your stock is down."
   - Good: "The market is filtering out your recent progress."
6. Greeting: Start with "Hi [Name]," (Never "Hey").
"""

# Archetype A: Research Hook (You did your homework)
# Archetype A: Research Hook (Transcript Analysis)
TRANSCRIPT_MINER_PROMPT = """Write ONE opening sentence for an email (Warm Intelligence).

CONTEXT:
- Company: {company_name}
- Contact: {contact_name}
- Something interesting you noticed: {friction_topic}
- Market vibe: {analyst_mood}
- Stock: {performance}%

YOUR APPROACH (The "Fiduciary Anxiety" Frame):
You read the transcript/notes and see a problem: a gap between what management says and what the market prices in. Frame this as a "misunderstanding" or "divergence."

GOOD EXAMPLES (Warm, Intelligent, Peer-to-Peer):
- "Hi {contact_name}, reading through the analyst notes, it felt like there is still a widening gap between your {friction_topic} and what the buy-side is actually pricing in."
- "Hi {contact_name}, looking at the market's reaction, it strikes me that investors are filtering out your recent progress on {friction_topic}."
- "Hi {contact_name}, it suggests to me that the market is still applying a discount to {company_name} that doesn't reflect the clarity you provided on {friction_topic}."

BAD EXAMPLES (Fake Surprise / Salesy / Naive):
- "I'm puzzled why..." ❌ (Fake surprise)
- "It's intriguing that..." ❌ (Fake surprise)
- "I noticed analyst skepticism..." ❌ (Too clinical)

STRICT RULES:
- Start with "Hi {contact_name},"
- Max 25 words (excluding greeting).
- No "Fake Surprise": BANNED "Intriguing", "Puzzled", "Crazy".
- Use: "It strikes me", "It suggests", "I noticed a divergence".
- Output ONLY the sentence. No quotes."""


# Archetype B: Comparison Hook (You noticed something interesting vs peers)
# Archetype B: Peer Gap (Valuation Divergence)
PEER_GAP_PROMPT = """Write ONE opening sentence for an email (Warm Intelligence).

CONTEXT:
- Company: {company_name}
- Contact: {contact_name}
- Their stock: {company_performance}% this year
- Peer: {peer_name}
- Peer Performance: {peer_performance}% this year
- Gap: {peer_name} is ahead by {gap}%

YOUR APPROACH (The "Complexity Discount" Frame):
Frame the valuation gap not as a failure, but as the market failing to understand their "operational resilience" or "structural efficiency."
CRITICAL: If {peer_name} is in a different sector (e.g. Bank vs Insurance), IGNORE IT. Use "sector index" or "wider market" instead.

GOOD EXAMPLES (Warm, Intelligent):
- "Hi {contact_name}, watching the recent sector rotation, it strikes me that the market is still applying a 'complexity discount' to your valuation."
- "Hi {contact_name}, looking at the divergence between {company_name} and the wider {peer_name} index, it suggests investors are filtering out the structural gains you've locked in."
- "Hi {contact_name}, it feels like the current share price serves as a 'legacy perception' tax that ignores your recent pivot."

BAD EXAMPLES (Financial Illiteracy / Fake Surprise):
- "It's intriguing that Commerzbank is soaring..." ❌ (Bad peer comparison)
- "I'm puzzled why you are down..." ❌ (Naive)
- "Your stock is underperforming..." ❌ (Attack)

STRICT RULES:
- Start with "Hi {contact_name},"
- Max 25 words (excluding greeting).
- Financial Literacy Check: NO cross-sector comparisons.
- No "Fake Surprise" ("Intriguing", "Puzzled").
- Output ONLY the sentence. No quotes."""


# Archetype C: Momentum Hook (Something interesting about where they're headed)
# Archetype C: Event/Momentum Hook (The Defense Frame)
EVENT_CONTEXT_PROMPT = """Write ONE opening sentence for an email (Warm Intelligence).

CONTEXT:
- Company: {company_name}
- Contact: {contact_name}
- Stock: {performance}% this year
- Event: {event_type}
- Narrative Risk: {narrative_risk}

YOUR APPROACH (The "Market Filtering" Frame):
Frame the current stock movement (or lack thereof) as the market "filtering out" their progress or "misunderstanding" the catalyst.

GOOD EXAMPLES (Warm, Intelligent):
- "Hi {contact_name}, with {event_type} approaching, it strikes me that the market is still filtering out the full impact of your strategic pivot."
- "Hi {contact_name}, watching {company_name}'s recent run, it feels like there is still a 'legacy discount' priced in that doesn't reflect your actual momentum."
- "Hi {contact_name}, reading the recent coverage, it suggests investors are still overly focused on {narrative_risk} and missing the structural efficiency story."

BAD EXAMPLES (Hype / Salesy):
- "Your stock is soaring!" ❌
- "I'd love to learn more..." ❌
- "With your Capital Markets Day coming up..." ❌ (Use "it strikes me..." frame instead)

STRICT RULES:
- Start with "Hi {contact_name},"
- Max 25 words (excluding greeting).
- No "Fake Surprise" ("Soaring", "Love", "Crazy").
- Use: "It strikes me", "It suggests", "It feels like".
- Output ONLY the sentence. No quotes."""


# =============================================================================
# ANTI-SPAM FILTER
# =============================================================================

BANNED_PHRASES = [
    "synergy", "synergies", "unlock value", "unlocking value",
    "innovative solution", "innovative solutions", "best-in-class",
    "i hope you are well", "i hope this finds you well",
    "leverage our", "leveraging", "game-changing", "paradigm",
    "circle back", "touch base", "low-hanging fruit",
    "value proposition", "at the end of the day"
]


def filter_spam(text: str) -> str:
    """
    Remove banned phrases from generated text.
    Returns cleaned text.
    """
    cleaned = text
    for phrase in BANNED_PHRASES:
        # Case-insensitive replacement with empty string
        import re
        cleaned = re.sub(re.escape(phrase), "", cleaned, flags=re.IGNORECASE)
    
    # Clean up any double spaces left behind
    cleaned = " ".join(cleaned.split())
    return cleaned.strip()


# -----------------------------------------------------------------------------
# PART 3: TRIGGER CLASSIFICATION
# -----------------------------------------------------------------------------

def get_trigger_type(event_type: str, performance: str = None) -> str:
    """
    Classifies the event into one of three trigger types:
    - EVENT: Capital Markets Day, CMD, Investor Day
    - LEADERSHIP: CFO Appointment, New CFO, Head of IR, appointed
    - VOLATILITY: Stock Drop, negative performance
    
    Returns: 'EVENT', 'LEADERSHIP', or 'VOLATILITY'
    """
    if not event_type:
        event_type = ""
    
    event_lower = event_type.lower()
    
    # Check for EVENT triggers
    event_keywords = ["capital markets day", "cmd", "investor day", "investor conference"]
    if any(kw in event_lower for kw in event_keywords):
        return "EVENT"
    
    # Check for LEADERSHIP triggers
    leadership_keywords = ["cfo appointment", "new cfo", "head of ir", "appointed", "appointment"]
    if any(kw in event_lower for kw in leadership_keywords):
        return "LEADERSHIP"
    
    # Check for VOLATILITY triggers (stock drop or negative performance)
    volatility_keywords = ["stock drop", "underperform", "dip", "decline", "drop"]
    if any(kw in event_lower for kw in volatility_keywords):
        return "VOLATILITY"
    
    # Check performance string for negative indicator
    if performance:
        perf_str = str(performance)
        if perf_str.startswith("-") or "down" in perf_str.lower():
            return "VOLATILITY"
    
    # Default to EVENT if unclear (most common trigger)
    return "EVENT"


def generate_hook_prompt(
    trigger_type: str,
    contact_name: str,
    company_name: str,
    event_date: str = None,
    role: str = None,
    performance: str = None,
    event_description: str = ""
) -> str:
    """
    Returns the appropriate meta-prompt for OpenAI based on trigger type.
    This prompt instructs the LLM to generate ONLY the opening hook sentence.
    """
    # Truncate description if too long to avoid token waste
    if not event_description: event_description = "No specific details provided."
    if len(event_description) > 300: event_description = event_description[:300] + "..."

    if trigger_type == "EVENT":
        return EVENT_TRIGGER_PROMPT.format(
            contact_name=contact_name,
            company_name=company_name,
            event_date=event_date or "an upcoming date",
            event_description=event_description
        )
    
    elif trigger_type == "LEADERSHIP":
        return LEADERSHIP_TRIGGER_PROMPT.format(
            contact_name=contact_name,
            company_name=company_name,
            role=role or "CFO",
            event_description=event_description
        )
    
    elif trigger_type == "VOLATILITY":
        return VOLATILITY_TRIGGER_PROMPT.format(
            contact_name=contact_name,
            company_name=company_name,
            performance=performance or "significantly",
            event_description=event_description
        )
    
    # Fallback to EVENT
    return EVENT_TRIGGER_PROMPT.format(
        contact_name=contact_name,
        company_name=company_name,
        event_date=event_date or "an upcoming date",
        event_description=event_description
    )


# -----------------------------------------------------------------------------
# PART 4: FINAL ASSEMBLY
# -----------------------------------------------------------------------------

def assemble_email(
    hook: str,
    contact_name: str,
    company_name: str,
    sender_name: str = "Your Name"
) -> str:
    """
    Concatenates [AI_Generated_Hook] + Static_Body_Template.
    Replaces placeholders with actual values.
    
    Returns: The complete email draft ready for the dashboard queue.
    """
    # Clean the hook (remove any quotes the LLM might have added)
    clean_hook = hook.strip().strip('"').strip("'")
    
    # Get first name from contact_name for greeting
    first_name = contact_name.split()[0] if contact_name else "there"
    
    # Format the static body with company name and sender
    body = STATIC_BODY_TEMPLATE.format(
        company_name=company_name,
        sender_name=sender_name
    )
    
    # Assemble final email
    email_draft = f"""Hi {first_name},

{clean_hook}

{body}"""
    
    return email_draft


# -----------------------------------------------------------------------------
# LEGACY COMPATIBILITY (for any code still using old interface)
# -----------------------------------------------------------------------------

# Keep old constants for backwards compatibility
PERSONAS = {
    "consultant": "You are a senior IR consultant at Quantifire. You are helpful, knowledgeable, and focus on strategic clarity.",
    "analyst": "You are a data analyst at Quantifire. You focus on market metrics, volatility, and measurable impact."
}

FRAMEWORKS = {
    "PAS": "Use the Hybrid Email Engine instead.",
    "DIRECT": "Use the Hybrid Email Engine instead."
}

def get_prompt(persona_key, framework_key, contact_name, company, event_type, event_title, performance_str):
    """
    DEPRECATED: Use generate_hook_prompt() + assemble_email() instead.
    This function is kept for backwards compatibility only.
    """
    # Redirect to new system
    trigger_type = get_trigger_type(event_type, performance_str)
    return generate_hook_prompt(
        trigger_type=trigger_type,
        contact_name=contact_name,
        company_name=company,
        event_date=None,
        role=None,
        performance=performance_str
    )


# =============================================================================
# ANALYST GRADE HOOK GENERATION
# =============================================================================
# Uses ANALYST_SYSTEM_PROMPT as the system message for OpenAI calls

def generate_consulting_grade_prompt(
    archetype: str,
    contact_name: str,
    company_name: str,
    context: dict
) -> str:
    """
    Generate the appropriate prompt for OpenAI based on archetype.
    
    Args:
        archetype: 'transcript_miner', 'peer_gap', or 'event_context'
        contact_name: First name of contact
        company_name: Company name
        context: Full context dict from personalization_research.get_personalization_context()
    
    Returns: Formatted prompt string for OpenAI
    """
    
    if archetype == "transcript_miner":
        tc = context.get("transcript_context", {})
        return TRANSCRIPT_MINER_PROMPT.format(
            contact_name=contact_name,
            company_name=company_name,
            sector=tc.get("sector", "N/A"),
            friction_topic=tc.get("friction_topic", "forward guidance"),
            analyst_mood=tc.get("analyst_mood", "seeking clarity"),
            performance=context.get("company_basics", {}).get("performance", 0)
        )
    
    elif archetype == "peer_gap":
        gap = context.get("peer_context", {}).get("gap_analysis", {})
        if not gap:
            # Fallback to event_context if no peer gap data
            return generate_consulting_grade_prompt("event_context", contact_name, company_name, context)
        
        return PEER_GAP_PROMPT.format(
            contact_name=contact_name,
            company_name=company_name,
            company_performance=gap.get("company_performance", 0),
            peer_name=gap.get("peer_name", "sector peer"),
            peer_performance=gap.get("peer_performance", 0),
            gap=gap.get("gap", 10)
        )
    
    else:  # event_context (default)
        ec = context.get("event_context", {})
        return EVENT_CONTEXT_PROMPT.format(
            contact_name=contact_name,
            company_name=company_name,
            performance=ec.get("performance", 0),
            event_type=ec.get("event_type", "neutral"),
            narrative_risk=ec.get("narrative_risk", "narrative may need sharpening"),
            urgency=ec.get("urgency", "now")
        )

